<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1530871307400" stop="1530871307436">
  <name>app_day_08_test.Scripts.test_001</name>
  <labels/>
  <test-cases>
    <test-case start="1530871307400" status="failed" stop="1530871307436">
      <name>Test_001.test_001_1</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;app_day_08_test.Scripts.test_001.Test_001 object at 0x06364E10&gt;

    def test_001_1(self):
    
&gt;       assert 0
E       assert 0

Scripts\test_001.py:8: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="1968-MainThread"/>
        <label name="host" value="theyoung-diannao"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
